import { useRef, useState } from 'react';
import { Linking, ScrollView, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Backdrop, Badge, Button, Card, Chip, Field, Heading, Notice, SectionTitle } from '@/components/ui';
import { CloudStatus } from '@/components/CloudStatus';
import { useTripLibrary } from '@/hooks/useTripLibrary';
import { useCloud } from '@/context/CloudContext';
import { useMyLocation } from '@/hooks/useMyLocation';
import { actionError, requestId } from '@/lib/api';
import { dayHikes, directionsURL, fetchDayWeather, finishTime, nepalToday, validateHikeDetails, validateWalkHours, type DayWeather } from '@/services/day-hike';
import { colors } from '@/theme/tokens';

export default function DayHikeScreen() {
  const library = useTripLibrary(); const personalId = useRef(requestId());
  const cloud = useCloud(); const gps = useMyLocation();
  const [step, setStep] = useState(0);
  const [editCoordinates, setEditCoordinates] = useState(false);
  const [selected, setSelected] = useState(dayHikes[0]); const [name, setName] = useState(dayHikes[0].name);
  const [place, setPlace] = useState(dayHikes[0].trailhead); const [origin, setOrigin] = useState('');
  const [latitude, setLatitude] = useState(String(dayHikes[0].latitude)); const [longitude, setLongitude] = useState(String(dayHikes[0].longitude));
  const [date, setDate] = useState(nepalToday); const [time, setTime] = useState('06:00');
  const [people, setPeople] = useState('4'); const [hours, setHours] = useState('6'); const [travel, setTravel] = useState('');
  const [weather, setWeather] = useState<{ key: string; value: DayWeather } | null>(null);
  const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const lock = useRef(false); const creation = useRef({ payload: '', id: requestId() });
  const weatherKey = `${date}/${latitude}/${longitude}`; const forecast = weather?.key === weatherKey ? weather.value : null;
  const finish = travel.trim() && Number(travel) >= 0 && Number(travel) <= 600 && Number(hours) > 0 && Number(hours) <= 16 ? finishTime(date, time, Number(hours), Number(travel)) : null;
  const copy = { color: colors.muted, fontSize: 14, lineHeight: 22 } as const;
  async function run(key: string, task: () => Promise<void>) { if (lock.current) return; lock.current = true; setBusy(key); setError(''); try { await task(); } catch (failure) { setError(actionError(failure)); } finally { setBusy(''); lock.current = false; } }
  function directions(mode: 'driving' | 'transit') { return run('directions', async () => { if (!place.trim()) throw new Error('Choose a trailhead or meeting point first.'); await Linking.openURL(directionsURL(place, origin, mode)); }); }
  return <Backdrop><ScrollView contentContainerStyle={{ padding: 20, gap: 18, paddingBottom: 48 }} keyboardShouldPersistTaps="handled">
    <Badge label="A DAY OUT · KATHMANDU & BEYOND" tone="lime" /><Heading title="City to trail. Together." subtitle="Choose where, when and who. Plan the ride to the trailhead separately from the hike." />
    <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>{dayHikes.map(hike => <Chip key={hike.id} label={hike.name} selected={selected.id === hike.id} onPress={() => { setSelected(hike); setEditCoordinates(hike.id === 'custom'); setName(hike.id === 'custom' ? '' : hike.name); setPlace(hike.trailhead); setLatitude(hike.latitude == null ? '' : String(hike.latitude)); setLongitude(hike.longitude == null ? '' : String(hike.longitude)); setHours(String(hike.hours)); setWeather(null); }} />)}</View>
    <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>{['Where & when', 'Get there', 'The walk', 'Weather', 'Your crew'].map((label, index) => <Chip key={label} label={`${index + 1} ${label}`} selected={step === index} onPress={() => setStep(index)} />)}</View>
    <Notice message={error} />
    {step === 0 && <Card><SectionTitle title="1 · PICK YOUR DAY" /><Field label="Hike name" value={name} onChangeText={setName} maxLength={60} placeholder="Phulchowki with friends" /><Field label="Trailhead / meeting place" value={place} onChangeText={value => { setPlace(value); setLatitude(''); setLongitude(''); setEditCoordinates(true); }} maxLength={200} placeholder="Confirmed park gate, village or bus stop" /><Text style={copy}>{selected.detail}</Text><Field label="Departure date · YYYY-MM-DD" value={date} onChangeText={setDate} maxLength={10} /><Field label="Leave your starting place at · Nepal time" value={time} onChangeText={setTime} placeholder="06:00" maxLength={5} /><Field label="Expected people · including you" value={people} onChangeText={setPeople} keyboardType="number-pad" maxLength={2} /></Card>}
    {step === 1 && <Card><SectionTitle title="2 · REACH THE TRAILHEAD" /><Field label="Starting place" value={origin} onChangeText={setOrigin} maxLength={200} placeholder="Your neighbourhood or meeting place" /><Button label="Use my current location" variant="outline" busy={gps.state === 'locating'} disabled={Boolean(busy)} onPress={() => void run('gps', async () => { const position = await gps.locate(); if (!position) throw new Error('Location unavailable. Enter a starting place instead.'); setOrigin(`${position.latitude},${position.longitude}`); })} /><Text style={copy}>From the city, compare a cab or a bus to the trailhead before walking. The buttons share your chosen start and destination with Google Maps. Transit information may be limited; confirm the stop, last bus and fare locally.</Text><Button label="Compare cab / road route & live ETA ↗" disabled={Boolean(busy)} onPress={() => void directions('driving')} /><Button label="Check bus / transit options ↗" variant="outline" disabled={Boolean(busy)} onPress={() => void directions('transit')} /><Field label="Approach time from your route check · minutes" value={travel} onChangeText={setTravel} keyboardType="number-pad" maxLength={3} placeholder="Enter the ETA shown by your routing app" /></Card>}
    {step === 2 && <Card><SectionTitle title="3 · PLAN THE WALK" /><Field label="Hike + breaks + return to trailhead · hours" value={hours} onChangeText={setHours} keyboardType="decimal-pad" maxLength={4} /><Text style={copy}>The initial hours are an editable planning allowance, not a measured route duration. Confirm the trail and pace with your group or guide. Road directions are not a hiking track.</Text>{finish ? <><Text style={{ color: colors.lime, fontSize: 19, fontWeight: '700', marginVertical: 12 }}>Back at trailhead ≈ {finish} NPT</Text><Text style={copy}>Based on your approach time and walking allowance. Add the journey home separately.</Text></> : <Text style={copy}>Add the approach time to calculate a planning finish time.</Text>}</Card>}
    {step === 3 && <Card><SectionTitle title="4 · WEATHER FOR YOUR DAY" /><Text style={copy}>Forecast at the trailhead area. Mountain conditions can differ. The forecast point is approximate. Use Adjust forecast location if your meeting place changes.</Text>{editCoordinates && <><Field label="Trailhead latitude" value={latitude} onChangeText={setLatitude} keyboardType="numbers-and-punctuation" /><Field label="Trailhead longitude" value={longitude} onChangeText={setLongitude} keyboardType="numbers-and-punctuation" /></>}<Button label={editCoordinates ? "Hide coordinate fields" : "Adjust forecast location"} variant="quiet" onPress={() => setEditCoordinates(value => !value)} /><Button label="Check this day’s forecast" busy={busy === 'weather'} disabled={Boolean(busy)} onPress={() => void run('weather', async () => { if (!latitude.trim() || !longitude.trim()) throw new Error('Add the trailhead coordinates first.'); const value = await fetchDayWeather(Number(latitude), Number(longitude), date); setWeather({ key: weatherKey, value }); })} />{forecast && <View style={{ gap: 8, marginTop: 12 }}><Text style={{ color: colors.ink, fontSize: 21, fontWeight: '700' }}>{forecast.min}–{forecast.max}°C · {forecast.rainChance}% rain chance</Text><Text style={copy}>{forecast.rainMm} mm precipitation · max wind {forecast.wind} km/h · sunset {forecast.sunset.slice(11, 16)} NPT</Text><Text style={copy}>{forecast.rainChance >= 50 || forecast.rainMm >= 10 ? 'Rain is plausible. Discuss wet trails, shelter and whether to postpone with your group.' : 'A low rain forecast does not guarantee dry or safe trails. Carry layers and check warnings again before departure.'}</Text>{finish && finish >= forecast.sunset.replace('T', ' ') && <Notice message="Your planned return is at or after sunset. Start earlier, shorten the walk and check gate closing times." />}<Text style={copy}>Open-Meteo · fetched {new Date(forecast.fetchedAt).toLocaleTimeString()} · forecast, not a safety clearance.</Text><Button label="Weather data by Open-Meteo · CC BY 4.0 ↗" variant="quiet" onPress={() => void run('source', () => Linking.openURL('https://open-meteo.com/en/licence'))} /></View>}<Button label="Official DHM warnings ↗" variant="quiet" onPress={() => void run('source', () => Linking.openURL('https://dhm.gov.np/'))} /></Card>}
    {step === 4 && <Card><SectionTitle title="5 · REVIEW & INVITE" /><Text style={{ color: colors.ink, fontSize: 18, fontWeight: '700', marginBottom: 8 }}>{name || 'Your hike'}</Text><Text style={copy}>{place || 'Meeting place needed'}{'\n'}{date} · {time} NPT · {people} people planned{'\n'}{hours} walking hours · {finish ? 'back at trailhead ≈ ' + finish : 'approach time not added'}</Text><Text style={copy}>Create the plan, then share an invitation link or invite existing Navo members by email. The people count is a planning target; nobody is added until they accept or you approve their request.</Text><Text style={copy}>Save a personal copy here first, even without a group connection. Your starting place is included in this device-only copy.</Text><Notice message={library.error} /><Button label="Save to my trips" busy={busy === 'save'} disabled={Boolean(busy) || !library.loaded} onPress={() => void run('save', async () => {
      const invalid = validateHikeDetails(name, place, date, time, people) || validateWalkHours(hours);
      if (invalid) throw new Error(invalid);
      const minutes = travel.trim() ? Number(travel) : null;
      if (minutes !== null && (!Number.isFinite(minutes) || minutes < 0 || minutes > 600)) throw new Error('Use an approach time between 0 and 600 minutes, or leave it blank.');
      await library.update(data => {
        const existing = data.trips.find(item => item.id === personalId.current);
        if (!existing && data.trips.length >= 100) throw new Error('Your library holds 100 plans. Remove an old plan before adding another.');
        const trip = { id: personalId.current, name: name.trim(), date, time, people: Number(people), meeting: place.trim(), origin: origin.trim(), walkingHours: Number(hours), approachMinutes: minutes, returnNotes: existing?.returnNotes ?? '', stayNotes: existing?.stayNotes ?? '', budgetPaisa: existing?.budgetPaisa ?? 0, expenses: existing?.expenses ?? [], updatedAt: new Date().toISOString() };
        return { ...data, trips: [trip, ...data.trips.filter(item => item.id !== trip.id)] };
      });
      router.push({ pathname: '/trip/[id]', params: { id: personalId.current } });
    })} /><CloudStatus /><Button label="Create hike group & invite people" busy={busy === 'create'} disabled={Boolean(busy) || !cloud.ready} onPress={() => void run('create', async () => {
      const invalid = validateHikeDetails(name, place, date, time, people) || validateWalkHours(hours);
      if (invalid) throw new Error(invalid);
      const payload = { name: name.trim(), trekId: 'custom-hike', startDate: date, outing: { destination: name.trim(), meetingPoint: place.trim(), startTime: time, expectedPeople: Number(people), walkingHours: Number(hours) } };
      const serialized = JSON.stringify(payload); if (creation.current.payload !== serialized) creation.current = { payload: serialized, id: requestId() };
      const group = await cloud.api<{ id: string }>('/groups', { ...payload, requestId: creation.current.id }); router.push(`/group/${group.id}`);
    })} /></Card>}
    <View style={{ flexDirection: 'row', gap: 12 }}>{step > 0 && <Button label="Back" variant="outline" style={{ flex: 1 }} onPress={() => setStep(value => value - 1)} />}{step < 4 && <Button label="Continue" style={{ flex: 1 }} onPress={() => { const invalid = step === 0 ? validateHikeDetails(name, place, date, time, people) : step === 2 ? validateWalkHours(hours) : null; setError(invalid || ''); if (!invalid) setStep(value => value + 1); }} />}</View>
    <Text style={copy}>Agree on the turnaround time, last return transport, water, food, emergency contact and who stays with the slowest member before setting off. Navo does not yet supply a verified trail track for these day hikes.</Text>
  </ScrollView></Backdrop>;
}
